# Generated by Django 6.0.5 on 2026-05-13 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('immatriculation_number', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('manufacture_year', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_USE', 'In Use'), ('IN_MAINTENANCE', 'In Maintenance'), ('IN_REPAIR', 'In Repair'), ('REFUELLING', 'Refuelling'), ('SPECIAL_ASSIGNMENT', 'Special Assignment'), ('RETIRED', 'Retired')], default='AVAILABLE', max_length=20)),
                ('current_mileage', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('MAINTENANCE', 'Routine Maintenance'), ('REPAIR', 'Repair')], default='MAINTENANCE', max_length=20)),
                ('action_taken', models.TextField()),
                ('completion_date', models.DateField()),
                ('next_service_mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mechanic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_jobs', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='fleet.vehicle')),
            ],
        ),
    ]
