# Generated by Django 6.0.5 on 2026-05-13 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shuttle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pickup_point', models.CharField(max_length=255)),
                ('scheduled_time', models.TimeField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sequence_number', models.PositiveIntegerField()),
                ('scheduled_time', models.TimeField()),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='routes.busline')),
            ],
            options={
                'ordering': ['sequence_number'],
            },
        ),
    ]
